name: Build and Deploy APIService

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate with gcloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIAL }}

      - name: Login to Docker registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Configure Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: |
            ${{ secrets.GCP_CREDENTIAL }}
          project_id: makeintheukservice
          skip_install: true

      - name: Echo secrets to file
        run: |
          echo "DB_USER=${{ secrets.DB_USER }}" >> makeintheuk-api/.env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> makeintheuk-api/.env
          echo "BUCKET_NAME=${{ secrets.BUCKET_NAME }}" >> makeintheuk-api/.env

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: mad123mano/truecallerservice:${{ github.sha }}
          args: |
            PYTHON_VERSION=3.8.15

      - name: Deploy to Google Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: truecallerwebcloudrun
          image: mad123mano/truecallerservice:${{ github.sha }}
          region: europe-west1
          platform: managed
          memory: 256Mi
          concurrency: 80
          max_instances: 5
